// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDNamUKrlES26sQ18B9ed7CUpgDfCeX64',
    appId: '1:1025510670675:web:1392fd5ab5a8a0b0b5a1a6',
    messagingSenderId: '1025510670675',
    projectId: 'just-watch-like',
    authDomain: 'just-watch-like.firebaseapp.com',
    storageBucket: 'just-watch-like.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH7jtzAm-byRDRRu112gG-Rs8ZTqXEJxk',
    appId: '1:1025510670675:android:d6d3a72294f95b30b5a1a6',
    messagingSenderId: '1025510670675',
    projectId: 'just-watch-like',
    storageBucket: 'just-watch-like.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh4aF3-oLa6SvdpH_Ni1H8fwFFwEeMpfg',
    appId: '1:1025510670675:ios:3b6412518e2c65edb5a1a6',
    messagingSenderId: '1025510670675',
    projectId: 'just-watch-like',
    storageBucket: 'just-watch-like.appspot.com',
    iosBundleId: 'com.example.justWatchLike',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh4aF3-oLa6SvdpH_Ni1H8fwFFwEeMpfg',
    appId: '1:1025510670675:ios:f42e339fff25fdbeb5a1a6',
    messagingSenderId: '1025510670675',
    projectId: 'just-watch-like',
    storageBucket: 'just-watch-like.appspot.com',
    iosBundleId: 'com.example.justWatchLike.RunnerTests',
  );
}
