import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'season_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'season_model.g.dart';

@freezed
class Season with _$Season {
  const factory Season({
    @JsonKey(name: 'episode_count') required int episodeCount,
    required int id,
    required String name,
    @JsonKey(name: 'poster_path') String? posterPath,
    @JsonKey(name: 'season_number') required int seasonNumber,
    @JsonKey(name: 'air_date') required String airDate,
  }) = _Season;

  // optional: Since our Person class is serializable, we must add this line.
  // But if Person was not serializable, we could skip it.
  factory Season.fromJson(Map<String, dynamic> json) => _$SeasonFromJson(json);
}
